### ISSUE TITLE
gamer.js unexpected end of input

### ISSUE THREAD

**Issue by SalmonSeasoning** [SalmonSeasoning/lchs-railers-esports-bot#2]
> bot_1         | /usr/src/bot/commands/gamer.js:41
> bot_1         | 
> bot_1         | 
> bot_1         | 
> bot_1         | SyntaxError: Unexpected end of input
> bot_1         |     at wrapSafe (internal/modules/cjs/loader.js:891:16)
> bot_1         |     at Module._compile (internal/modules/cjs/loader.js:941:27)
> bot_1         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
> bot_1         |     at Module.load (internal/modules/cjs/loader.js:822:32)
> bot_1         |     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
> bot_1         |     at Module.require (internal/modules/cjs/loader.js:864:19)
> bot_1         |     at require (internal/modules/cjs/helpers.js:74:18)
> bot_1         |     at /usr/src/bot/entry.js:19:5
> bot_1         |     at Array.forEach (<anonymous>)
> bot_1         |     at Object.<anonymous> (/usr/src/bot/entry.js:16:30)
> bot_1         | /usr/src/bot/commands/gamer.js:41
> bot_1         | 
> bot_1         | 
> bot_1         | 
> bot_1         | SyntaxError: Unexpected end of input
> bot_1         |     at wrapSafe (internal/modules/cjs/loader.js:891:16)
> bot_1         |     at Module._compile (internal/modules/cjs/loader.js:941:27)
> bot_1         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
> bot_1         |     at Module.load (internal/modules/cjs/loader.js:822:32)
> bot_1         |     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
> bot_1         |     at Module.require (internal/modules/cjs/loader.js:864:19)
> bot_1         |     at require (internal/modules/cjs/helpers.js:74:18)
> bot_1         |     at /usr/src/bot/entry.js:19:5
> bot_1         |     at Array.forEach (<anonymous>)
> bot_1         |     at Object.<anonymous> (/usr/src/bot/entry.js:16:30)
> bot_1         | /usr/src/bot/commands/gamer.js:41
> bot_1         | 
> bot_1         | 
> bot_1         | 
> bot_1         | SyntaxError: Unexpected end of input
> bot_1         |     at wrapSafe (internal/modules/cjs/loader.js:891:16)
> bot_1         |     at Module._compile (internal/modules/cjs/loader.js:941:27)
> bot_1         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
> bot_1         |     at Module.load (internal/modules/cjs/loader.js:822:32)
> bot_1         |     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
> bot_1         |     at Module.require (internal/modules/cjs/loader.js:864:19)
> bot_1         |     at require (internal/modules/cjs/helpers.js:74:18)
> bot_1         |     at /usr/src/bot/entry.js:19:5
> bot_1         |     at Array.forEach (<anonymous>)
> bot_1         |     at Object.<anonymous> (/usr/src/bot/entry.js:16:30)
>

**Comment by SalmonSeasoning** [comment]
Currently this file has .ignore at the end of it to prevent being included by the bot (just so it can run!)

**Comment by iComputer7** [comment]
Resolved by 185713d
